# Generated by Django 3.2.17 on 2023-03-05 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_lending_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lending',
            old_name='State',
            new_name='state',
        ),
    ]
